### ISSUE TITLE
Deb package

### ISSUE THREAD

**Issue by dolohow** [RicinApp/Ricin#110]
Please provide deb packages.

Thank you.

**Comment by SkyzohKey** [comment]
Hi.
I'll probably setup a Debian VM and provides a deb package, but currently I have many bugs to fix ^^

**Comment by dolohow** [comment]
I understand, bugs are more important! But think you for your promising answer.

**Comment by SkyzohKey** [comment]
Anyway, if you know how to make .deb packages, feel free to make a .sh script, I would be pleased to add it to our Travis YAML in order to have up-to-date .deb's ;)

**Comment by dolohow** [comment]
I will see what I can do.

**Comment by SkyzohKey** [comment]
@dolohow Did u succeed ? :p

**Comment by Encrypt** [comment]
Deb packages are on their way @dolohow!
I have recently created a BASH script to build Tox clients and among others, Ricin.
It is published here: https://github.com/Encrypt/toxdeb

@SkyzohKey tested a build yesterday that I ran and it seems to work.
You'll soon be able to get Ricin as a .deb! ;)

**Comment by dolohow** [comment]
I am glad to hear that, unfortunately I did not have time to do it myself which is a shame.  If you could further provide ppa for Ubuntu that would be even better.

Thank you.

**Comment by Encrypt** [comment]
"Soon" has now arrived @dolohow!
Ricin is now packaged for Ubuntu Wily & Xenial / Debian Strech & Sid.

If your distribution is listed above, run the following commands:

```
echo "deb https://pkg.tox.chat/debian stable xenial" | sudo tee /etc/apt/sources.list.d/tox.list
wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install ricin
```

Sorry for the delay!

**Comment by dolohow** [comment]
It works!  The only issue I have is that Ricin got no icon.

**Comment by Encrypt** [comment]
Indeed, it looks like the icons of Ricin are not installed in the .deb package.
Thanks for reporting @dolohow !

@SkyzohKey : Could you see if you can fix that?
I'm sure this bug comes from your waf configuration.
