### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by Sorunome** [RicinApp/Ricin#112]
## Summary
- Archlinux
- 0.0.6.1
- 5372543
- gtk3 3.20.3-1  
- **Reproducible:** Always

The style of ricin is quite off (obvious red box spoiler is obvious): https://img.ourl.ca/34.png

When making https://github.com/RicinApp/Ricin/blob/master/res/themes/reset.css look like http://pastebin.com/7P4Dw8eV it will fix most issues, not all, buttons are a bit too dark and the switch-boxes in "Interface" are invisible and other small things.

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

Note: I'm completly rewriting Ricin, so this issue will be fixed in the `rewrite-clean` branch.
