### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by eternal-sorrow** [RicinApp/Ricin#122]
I've already wrote to tox-overlay (Tox/gentoo-overlay-tox#5), but no one answered me there. Could you please influence people there?

**Comment by eternal-sorrow** [comment]
any news?

**Comment by SkyzohKey** [comment]
I dont work anymore on the master branch since I started to rewrite Ricin from scratch in the develop branch ^^

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
