### ISSUE TITLE
Ricin dies with "Operation not supported" message

### ISSUE THREAD

**Issue by yurivict** [RicinApp/Ricin#123]
I tried to make a FreeBSD port, but Ricin dies:

```
$ ricin

(ricin:81065): GLib-CRITICAL **: g_setenv: assertion 'value != NULL' failed

** (ricin:81065): CRITICAL **: file Ricin.c: line 304: uncaught error: Operation not supported (g-io-error-quark, 15)
```

System calls before the error message:

```
access("/home/yuri/.config/tox//ricin.json",F_OK) ERR#2 'No such file or directory'
issetugid()                                      = 0 (0x0)
issetugid()                                      = 0 (0x0)
getpid()                                         = 81039 (0x13c8f)

** (ricin:81039): CRITICAL **: file Ricin.c: line 304: uncaught error: Operation not supported (g-io-error-quark, 15)
```
## Summary
- **Operating System + version:**  FreeBSD 10.3
- **Ricin's version:**  0.1.0
- **GTK+ version:**  3.18.8
- **ToxCore version:**  0.151112
- **Reproducible:** Always

**Comment by SkyzohKey** [comment]
Yeah that's a known issue caused by Ricin not being able to copy default settings file at the first launch iirc, try to run it as sudo first time you launch it. I'll fix that soon ;)
