### ISSUE TITLE
Ricin.c: line 304: uncaught error: Operation not supported (g-io-error-quark, 15)

### ISSUE THREAD

**Issue by probonopd** [RicinApp/Ricin#124]
I am trying to build an [AppImage](http://appimage.org/) from the Travis CI build products.
## Summary
- **Operating System + version:**  Ubuntu 16.04 LTS 64-bit
- **Ricin's version:**  https://transfer.sh/m1TE4/ricin-git6530aa9-glibc-x86-64.appimage
- **Ricin's commit hash:**  6530aa9 from https://github.com/probonopd/Ricin
- **GTK+ version:**  3.0.0
- **ToxCore version:** git
- **Hardware:**  x86_64
- **Reproducible:** _(Always)_
## Steps to reproduce:

_Please provide detailed steps in order for us to reproduce the issue_
1.  wget -c https://transfer.sh/m1TE4/ricin-git6530aa9-glibc-x86-64.appimage 
2.  chmod a+x ricin-git6530aa9-glibc-x86-64.appimage
3.  ./ricin-git6530aa9-glibc-x86-64.appimage
## Observed Behavior:

I am trying to generate an [AppImage](http://appimage.org/) from the Travis CI build products. This seems to _almost_ work, but when I try to run Ricin, then I get

```
** (ricin:4673): CRITICAL **: file Ricin.c: line 304: uncaught error: Operation not supported (g-io-error-quark, 15)
```
## Expected Behavior:

Application should launch without `g-io-error-quark`
## Additional infos:

Here is the script that generates the AppImage:
https://github.com/probonopd/Ricin/blob/master/appimage.sh

Since it takes the existing build product, I suspect the error has nothing to do with the AppImage bundling; I might be wrong though.

**Comment by SkyzohKey** [comment]
Yeah, I just fixed this bug in the commit 1ee19a3e393b4963112c3a41c01d9bfee97f510a.
Anyway, I saw that you were doing it (travis irc notification héhé) and I would like to thanks you for this cool job !

Just saw a little bug with the .appimage I tried from the build on your travis: (Gtk) icons are missing. :/
