### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by afreakk** [RicinApp/Ricin#125]
Hi, is there any way of changing font size in ricin ?

**Comment by SkyzohKey** [comment]
Currently not, but yeah, I'll add this to my todo list. :)

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

**Note**: I added this suggestion to my todo list and i'll probably write this in the `rewrite-clean` branch once I'll do the GUI.
