### ISSUE TITLE
AppImage doesn't work on elementary OS 0.3.2 (based on Ubuntu 14.04)

### ISSUE THREAD

**Issue by probonopd** [RicinApp/Ricin#127]
As mentioned [here](https://github.com/RicinApp/Ricin/pull/126#issuecomment-221140942):

> AppImage doesn't work on elementary OS 0.3.2 (based on Ubuntu 14.04).

This is because the Ricin AppImage needs a newer version of Gtk stuff than what is in Ubuntu 14.04.

Would it be possible to compile Ricin on trusty without the need for `ppa:rebuntu16/glade-3.19+-trusty`? Then it would not require so new Gtk libraries and the resulting AppImage would run on more systems. 

Alternatively, we can try to bundle more libraries pulled in from that ppa inside the AppImage, which should also make it more compatible with older distros but would also increase the download size of the AppImage.

**Comment by probonopd** [comment]
Try this build:
https://transfer.sh/ft1mM/ricin-git4c971f7-glibc-x86-64.appimage
Here I included the additional libraries. Download size is not too bad.
Runs for me on Ubuntu 14.04, didn't try on others so far.

Updated script is [here](https://github.com/probonopd/Ricin/blob/master/appimage.sh).

**Comment by GranPC** [comment]
It works! Thank you :)

**Comment by SkyzohKey** [comment]
> Would it be possible to compile Ricin on trusty without the need for `ppa:rebuntu16/glade-3.19+-trusty`?

This ppa is needed cuz Ricin needs `Gtk+ >= 3.16.4`, else it'll fail compiling (cuz `Gtk < 3.16` doesn't had Popovers and ListStore :anguished:)

But anyway, if this update doesn't introduce regressions, could you open a new pull-request for this update? :)

**edit**: People on openSuSe Tumbleweed reported me this:

``` shell
fuse: failed to exec fusermount: No such file or directory
Could not mount AppImage
```

**Comment by probonopd** [comment]
For FUSE, please see https://github.com/probonopd/AppImageKit/wiki/FUSE

openSUSE users can set up FUSE with

```
sudo zypper install fuse
```

If you don't want to install FUSE, you can either mount or extract the AppImage. To mount the AppImage and run the application, simply run

```
sudo mount -o loop Some.AppImage /mnt
/mnt/AppRun
```
