### ISSUE TITLE
PGP plugins to encrypt messages before sending them in ToxCore DHT.

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#13]
It think that we should provide a plugin (or an app feature) to let the user setting a PGP key making it (the user) able to encrypt messages using PGP/GPG before sending them to the Tox handle.

If well implemented it would really good → even if Tox does eventually have a backdoor or some bug that breaks its security this PGP support will make sure it's still safe.
##

**Comment by benwaffle** [comment]
If Tox has a backdoor, nobody will use it even if you add PGP on top. Also, no other clients support this.

**Comment by aaannndddyyy** [comment]
An additional layer providing additional security is not a bad idea, however, I don't know if PGP is the right choice for a chat application. 
Why not go with OTR?
OTR is save even over insecure channels, so if tox proves insecure, you'd still be secure, just as with PGP, but you would still have perfect forward secrecy and deniable authentication

**Comment by SkyzohKey** [comment]
Does OTR provide user authentication like PGP does?

**Comment by aaannndddyyy** [comment]
Yes

**Comment by SkyzohKey** [comment]
@aaannndddyyy nice, so it could be PGP and/or OTR :)

**Comment by aaannndddyyy** [comment]
yes, you could have two plugins, or one that provides both. but OTR should be the priority of the two, in case you have to decide.
User authentication with OTR is such that you can be sure that the messages are coming from the perso you think they come from, but at the same time your contact can be sure that you cannot prove to a thir party that he/she said what he/she said. That's called deniable authentication - as oposed to on the one hand unauthenticate normal messages like sms where you don't know if the message really came from Alice, and signed messages in pgp on the other hand, where Bob can prove to Malroy that Alice said what she said.

**Comment by aaannndddyyy** [comment]
So this will not come?

**Comment by SkyzohKey** [comment]
Not for now, i'll reopen when the plugin system is ready ;)
