### ISSUE TITLE
Double click to change name/status

### ISSUE THREAD

**Issue by abueide** [RicinApp/Ricin#130]
Also should be canceled when it loses focus.

**Comment by SkyzohKey** [comment]
Can you please provides more informations?

**Comment by abueide** [comment]
@SkyzohKey I'm talking about these http://pix.toile-libre.org/upload/original/1464135910.png

**Comment by SkyzohKey** [comment]
Ah, that's already the case but yeah I need to fix the selection color. Currently the selected text have the same color as the background, so that's confusing. I'll add this on the Todo list. Thanks for the report. :)

**Comment by abueide** [comment]
@SkyzohKey I meant instead of clicking once to trigger the edit, to instead require double clicking to trigger the edit to prevent misclicks. Also it should cancel the change and go back to normal if it loses focus by selecting somewhere else. It does cancel when I click on a button that performs an action, but not when i click in blank space which it should.

**Comment by SkyzohKey** [comment]
Ah, yes you're right. I'll probably do this part of the massive refactoring ;)

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

Note: I'm completly rewriting Ricin, so this issue will be fixed in the `rewrite-clean` branch.
