### ISSUE TITLE
Cannot connect to Tox network

### ISSUE THREAD

**Issue by Ogromny** [RicinApp/Ricin#132]
Quand j'ouvre Ricin, je séléctionne mon profil, je click je peut attendre 30min, je n'arrive pas à me connecter au réseau l'icone status reste rouge

**Comment by Ogromny** [comment]
EDIT: Ça m'a soulé j'ai supprimer le dossier tox, et je me suis crée un nouveau toxid.

**Comment by SkyzohKey** [comment]
T'as essayé de vérifier ton pare-feu avant de tout supprimer bouffon? x)

**Comment by Ogromny** [comment]
Ouais mdr, ça marche pas. Donc je me suis refait un compte .tox, mais je peux pas add d'amis le bug du bouton x)

**Comment by SkyzohKey** [comment]
Envoies ton ToxID x)

**Comment by Ogromny** [comment]
3400948AF5608E97D62C1C43D339B984EF9CB66834AE64DF68564A3DCAE2631731CC5B6B9313
