### ISSUE TITLE
symbol lookup error: ./lib/libgtk-3.so.0: undefined symbol: g_list_model_get_type

### ISSUE THREAD

**Issue by PhelanBavaria** [RicinApp/Ricin#135]
I'm on the newest Debien Jessie with the newest installation of tox and Ricin.

Installation as instructed on this github page (below Download)

On the last step (./ricin-0.1.1.app) I get an error:
/tmp/.mount_E462Ym/usr/bin/ricin.wrapper
zenity, kdialog, Xdialog missing. Skipping ./bin//ricin.wrapper.
/tmp/.mount_E462Ym/usr/bin/ricin: symbol lookup error: ./lib/libgtk-3.so.0: undefined symbol: g_list_model_get_type

**Comment by SkyzohKey** [comment]
@probonopd Hmm ?
@PhelanBavaria I would ask you to report me the result of `./ricin-0.1.1.app --version` please

**Comment by PhelanBavaria** [comment]
> /tmp/.mount_Fm9P5W/usr/bin/ricin.wrapper
> zenity, kdialog, Xdialog missing. Skipping ./bin//ricin.wrapper.
> /tmp/.mount_Fm9P5W/usr/bin/ricin: symbol lookup error: ./lib/libgtk-3.so.0: undefined symbol: g_list_model_get_type

That is what I get.

**Comment by SkyzohKey** [comment]
@PhelanBavaria Ok, it seems that your GTK+3 version is lower than 3.16.4 :x

**Comment by PhelanBavaria** [comment]
I see, isn't it supposed to work with Debian out of the box?

**Comment by SkyzohKey** [comment]
It is. :x 
@probonopd cant we have a min gtk3 version in appimages ?

**Comment by probonopd** [comment]
@SkyzohKey we could bundle GTK+3 inside the AppImage. Then it would run on older systems too, but the AppImage would become larger. Is that what you want? Alternatively, we could do a small zenity script informing the user that GTK+3 >= 3.16.4 is required if it is not there.

**Comment by SkyzohKey** [comment]
> Alternatively, we could do a small zenity script informing the user that GTK+3 >= 3.16.4 is required if it is not there.

@probonopd Seems to be the best solution x)

**Comment by aaannndddyyy** [comment]
./ricin-0.1.1.app 
/tmp/.mount_YUObbY/usr/bin/ricin.wrapper
zenity, kdialog, Xdialog missing. Skipping ./bin//ricin.wrapper.
/tmp/.mount_YUObbY/usr/bin/ricin: symbol lookup error: ./lib/libatk-1.0.so.0: undefined symbol: g_type_check_instance_is_fundamentally_a

./ricin-0.1.1.app --version
/tmp/.mount_q66s9V/usr/bin/ricin.wrapper
zenity, kdialog, Xdialog missing. Skipping ./bin//ricin.wrapper.
/tmp/.mount_q66s9V/usr/bin/ricin: symbol lookup error: ./lib/libatk-1.0.so.0: undefined symbol: g_type_check_instance_is_fundamentally_a

**Comment by probonopd** [comment]
@aaannndddyyy which base system (distribution and version) are you running this on?

**Comment by aaannndddyyy** [comment]
@probonopd I'm on Trisquel Mini gnu/linux, version 7, based on ubuntu. 
LXDE
I followed the instructions, i.e. did wget, chmod and ./ricin-0.1.1.app

**Comment by probonopd** [comment]
@aaannndddyyy it's based on Ubuntu 14.04 LTS so I would assume your GTK+ version is lower than 3.16.4 which is the minimum requirement for Ricin according to @SkyzohKey
