### ISSUE TITLE
Build issue: valac-0.8 not found. Xubuntu 16.0.4. LTS.

### ISSUE THREAD

**Issue by kxxvii** [RicinApp/Ricin#140]
## Summary
- **Operating System + version**: Xubuntu 16.04 LTS
- **Ricin's version**: 0.2.3  
- **Ricin's commit hash**: 4df2a28a587744ebe2a68e23ee0f313ed6d3db8b
- **GTK+ version**: 3.0  
- **ToxCore version**: 0.1.3758.532629d-1  
- **Hardware**: --  
- **Reproducible**: Always
## Steps to reproduce:

_Please provide detailed steps in order for us to reproduce the issue_
1.  downloaded the source code
2.  tried to compile it using make
3.  ./waf configure ran
4.  found all programs and packages except valac-0.8
## Observed Behavior:

 Can't find valac-0.8, build process stopped
## Expected Behavior:

 Finding valac-0.8/equivalent and let me build from source. valac-0.8 has been superseded.
##

**Comment by SkyzohKey** [comment]
You need to install `valac-0.30` in order to have ricin to compile, then do the following :

```
./waf configure build 
sudo ./waf install
```

**Comment by kxxvii** [comment]
I had valac-0.30 installed at the time I opened the issue. The same thing happened with a previous release as well. Tried it again after I double-checked that the dependencies where satisfied and the error still occur.

**Comment by Encrypt** [comment]
Ricin is now built on build.tox.chat for Ubuntu Xenial. You should be able to apt-get it if you wish!

To download ricin for Ubuntu Xenial, run:

```
echo "deb https://pkg.tox.chat/debian stable xenial" | sudo tee /etc/apt/sources.list.d/tox.list
wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install ricin
```

Note that contrary to what is written on the tox.chat website, ricin can only be obtained using `deb https://pkg.tox.chat/debian stable xenial` for the moment, as aforementioned.
Once @SkyzohKey fixes his develop branch, nightly packages of ricin will be downloadable using `deb https://pkg.tox.chat/debian nightly xenial`.

**Comment by kxxvii** [comment]
@Encrypt : Thanks for the tip. That works for me although I was able to use Ricin by using the Appimage mentioned in the README. 

However, building it by using the aforementioned steps still isn't possible for me. Tried again just for the sake of it. If this is important or not I'll let the developer and other tox-client developers decide. Therefore I won't close the issue.

**Comment by Encrypt** [comment]
@kxxvii : Ricin is currently built in the Xenial chroot with the package `valac` and not `valac-0.30` / `valac-0.8`.
Could you try installing that package and building Ricin again?

Also, regarding the AppImage, although it works this way I'd recommend using the pkg.tox.chat repository instead! ;)

**Comment by kxxvii** [comment]
@Encrypt  That's the package I've used and from what I gather it installs valac-0.30. It's described here http://packages.ubuntu.com/xenial/amd64/valac/filelist

**Comment by Encrypt** [comment]
Well... that's weird I have to say.
Do you have an idea why @SkyzohKey ?

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
