### ISSUE TITLE
Can't add a friend

### ISSUE THREAD

**Issue by kb2623** [RicinApp/Ricin#142]
## Summary
- **Operating System + version:** Manjaro 16.06
- **Ricin's version:**  it should be 0.2.1 but it says that is 0.1.0
- **GTK+ version:**  3.20
- **ToxCore version:**  toxcore-3747-1
- **Reproducible:** Always
## Steps to reproduce:
1.  Press on button for adding friends
2.  Button for adding friends and button for settings disappear 
3.  Nothing shows up
## Observed Behavior:

Button for adding friends dos not work on my system.

**Comment by inmylo** [comment]
Same problem on ArchLinux x64, with Gnome and latest updates (23.07.2016), installed from AUR. Buttons "Add a friend" and "Settings" just disappear. When started from terminal no error messages appear.

Ricin 0.2.1-1-x86_64

**Comment by Esption** [comment]
Same here on Gentoo, perhaps a GTK+3.20 issue?  I'm getting it with both the latest git and Ricin v0.2.3.  When pushing the settings button I get

> (ricin:27033): Gtk-CRITICAL **: gtk_list_box_unselect_row: assertion 'GTK_IS_LIST_BOX_ROW (row)' failed

And when I push the add a friend button it just closes that little tab w/o a message.  Also when it boots up the (non-theme deprecation) errors that it prints out are

> (ricin:27033): Gtk-CRITICAL **: gtk_entry_set_text: assertion 'text != NULL' failed
> 
> (ricin:27033): Gtk-WARNING **: GtkListBox with a model will ignore sort and filter functions

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

Note: I'm completly rewriting Ricin, so this issue will be fixed in the `rewrite-clean` branch.
