### ISSUE TITLE
Contact online notification pops all the time

### ISSUE THREAD

**Issue by eternal-sorrow** [RicinApp/Ricin#143]
## Summary
- **Operating System + version:**  gentoo
- **Ricin's version:**  0.2.3
- **Ricin's commit hash:** f79a115c9640995559caf0b20796ce0f716b1f45 
- **GTK+ version:**  3.20.6-r1
- **ToxCore version:**  latest from git irungentoo/toxcore@755f084e8720b349026c85afbad58954cb7ff1d4
- **Hardware:**  x86_64
- **Reproducible:** Almost Always
## Steps to reproduce:
1.  start ricin
2.  login under profile with at least one contact
3.  get the online notification annoyingly popping
## Observed Behavior:

Contact online notification popping from time to time (~5 - 10 sec)
## Expected Behavior:

Contact online notification should pop when it comes from offline
## Additional infos:

Also I'm getting the default dark theme after restart (I've changed it to white). In settings it's set to white. Changing it to dark and back to white makes it white.

**Comment by SkyzohKey** [comment]
Ok, the notification issue should be gone now. Thanks for the report.
You may have to `git pull` and recompile Ricin  from the latest master.

### New in the latest commits:
- Fix for the notifications issue (I plan to add a settings tabs for handling Notifications)
- Some new features like:
  - Pasting an image to send it ;
  - The ability to localy remove a message from the chatview ;
  - The ability to clear the chatview completly.

I'm gonna investigate about your theme issue. ;)

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

Note: I'm completly rewriting Ricin, so this issue will be fixed in the `rewrite-clean` branch.
