### ISSUE TITLE
Add smiles

### ISSUE THREAD

**Issue by Ygarr** [RicinApp/Ricin#144]
Need add smiles. 

Those smiles sub-functionality that already is -  not working. Can not add them to the message field and send.

The good (not worst anyway) example is qtox project smiles:
https://github.com/qTox/qTox/tree/master/smileys

**Comment by SkyzohKey** [comment]
Ricin `master` branch development is currently stopped as I'm working on rewriting it from scratch, with clean code on the `rewrite-clean` branch. But anyway I already planed to implement emojis packs ;)
