### ISSUE TITLE
Windows (7): Ricin does not import control Assets (ie window controls)

### ISSUE THREAD

**Issue by AyoungDukie** [RicinApp/Ricin#146]
Most of the basic interface images fail to load within the app, per the screenshot below:

![image](https://cloud.githubusercontent.com/assets/5449443/19353899/d9fb0754-9132-11e6-8cdf-b5a6a8896718.png)

The brightside is that the tool-tips do load when you hover over them!

The cmd prompt has these readouts when loading (it appears to be flooded with failed loading of GTK assets?). 

![image](https://cloud.githubusercontent.com/assets/5449443/19354300/373d2522-9134-11e6-8a22-590332ee8ba2.png)

![image](https://cloud.githubusercontent.com/assets/5449443/19354160/cd8d5034-9133-11e6-95b9-f1f4d29d648e.png)

![image](https://cloud.githubusercontent.com/assets/5449443/19354109/a53b55ae-9133-11e6-9025-adaecc23182c.png)

![image](https://cloud.githubusercontent.com/assets/5449443/19354078/86c2528a-9133-11e6-9262-8afbd38089c7.png)

**Comment by SkyzohKey** [comment]
Hey!  
Ricin `master` branch is currently deprecated as I'm working on rewriting Ricin from scratch, with clean codebase. Development now takes place on the `rewrite-clean` branch.

Contributions to the master branch are likely to be ignored and instead you should consider using another Tox client _(uTox, qTox, Toxygen, ...)_ that may fit your needs until Ricin v2 is ready to _dominate the world!_

Anyway, the way i did the Windoesn't build is probably one of the reasons that make Ricin unusable on that unusable OS ;)

**Comment by AyoungDukie** [comment]
Haha, that sounds good, apologies for posting so many issues in the old branch. And yes, unfortunately for me the engineering tools I need for work are Windows only... I have my assortment of tools to make it more Nix-like to help ease the experience, so I make do!
