### ISSUE TITLE
Windows (7): Ricin crashes when attempting to change Avatar

### ISSUE THREAD

**Issue by AyoungDukie** [RicinApp/Ricin#147]
Clicking the Change Avatar button causes an immediate crash, filling the cmd prompt with the message below and popping up the alert shown:

![image](https://cloud.githubusercontent.com/assets/5449443/19354501/e7ffcf5e-9134-11e6-8215-94991b3a0773.png)

Potentially seems to be related to #146  and GTK asset retrieval (GLib not imported?)

Thanks for all of your hard work!

**Comment by SkyzohKey** [comment]
Hey!  
Ricin `master` branch is currently deprecated as I'm working on rewriting Ricin from scratch, with clean codebase. Development now takes place on the `rewrite-clean` branch.

Contributions to the master branch are likely to be ignored and instead you should consider using another Tox client _(uTox, qTox, Toxygen, ...)_ that may fit your needs until Ricin v2 is ready to _dominate the world!_
