### ISSUE TITLE
Windows (7) Feature Request: Import Profiles from install or "profiles" directory

### ISSUE THREAD

**Issue by AyoungDukie** [RicinApp/Ricin#148]
The Linux version of Ricin (at least the AppImage version) will pull/import *.tox profile files from the installed directory. Currently in Windows, it appears to only import/load files from the user's ".../Appdata/Local/tox" folder, which would be somewhat similar to needing to put data in the "/opt/... " folders in Linux. It works, however it can be fairly unintuitive for new users. Is there a way to allow the program to import from a folder that is easier for users to access?

**Comment by SkyzohKey** [comment]
Hey!  
Ricin `master` branch is currently deprecated as I'm working on rewriting Ricin from scratch, with clean codebase. Development now takes place on the `rewrite-clean` branch.

Contributions to the master branch are likely to be ignored and instead you should consider using another Tox client _(uTox, qTox, Toxygen, ...)_ that may fit your needs until Ricin v2 is ready to _dominate the world!_
