### ISSUE TITLE
No updates of AppImage builds since 0.2.1

### ISSUE THREAD

**Issue by strixaluco** [RicinApp/Ricin#151]
Thank you for developing Ricin, it looks really nice. 
Sorry if it's not the proper place, but are there any updates for AppImage builds planned? I've checked back down from 0.2.8, but the most recent one accessible seems to be 0.2.1. There were lots of bug fixes and improvements since that version, hence it would be nice to have them in the build. Thanks.

**Comment by SkyzohKey** [comment]
Yeah, appimages builds are broken and I have to wait @probonopd for a fix, dunno what it broken. I'll investigate thanks for the report guy ;)

**Comment by probonopd** [comment]
Hi @SkyzohKey where can I see a log of a failed AppImage build?

**Comment by strixaluco** [comment]
@SkyzohKey not at all :) Thanks for looking into this.

**Comment by SkyzohKey** [comment]
@probonopd Just download ie. this build: https://transfer.sh/2g97j/ricin-git7cf32ff-glibc2.14-x86-64.appimage and try to launch it, it will fail :x  
@strixaluco Thx to u for reporting the issue, anyway you can download Ricin on the official website as both HTTPS and Torrent ways. https://ricin.im/downloads.html#linux

**Comment by probonopd** [comment]
@SkyzohKey can you give the link to the Travis build log of this build?

**Comment by SkyzohKey** [comment]
@probonopd Yeah sure here you go: https://travis-ci.org/RicinApp/Ricin/builds/171881942

**Comment by probonopd** [comment]
> @probonopd Just download ie. this build: https://transfer.sh/2g97j/ricin-git7cf32ff-glibc2.14-x86-64.appimage and try to launch it, it will fail :x

Sees to run for me on Xubuntu 16.04. What exactly is the issue?

**Comment by SkyzohKey** [comment]
``` sh
λ skyzohkey [~/Downloads] → ./ricin-git7cf32ff-glibc2.14-x86-64.appimage
/home/skyzohkey/.cache/thumbnails/normal/bc8e6bb73bc3294131d56e20407549bc.png is missing.
Probably not running ./bin//ricin.wrapper from within an AppImage.
Hence falling back to using .DirIcon
zenity, kdialog, Xdialog missing. Skipping ./bin//ricin.wrapper.
/tmp/.mount_khpUWC/usr/bin/ricin: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
```

**Comment by probonopd** [comment]
Is `libpcre.so.3` missing from your base system, and which distribution are you running? What happens if you add `libpcre.so.3` to the libraries bundled in the AppImage?

**Comment by SkyzohKey** [comment]
@probonopd I'm using Fedora 23 and libpcre is there as `libpcre.so`, `libpcre.so.1` and `libpcre.1.2.7`, also how to add it to the libraries ?

**Comment by probonopd** [comment]
At build time on Travis, copy it into the AppDir before the AppImage is generated. Actually I wonder why it got removed/not bundled in the first place since libpcre.so.3 is no longer on the [excludelist](https://github.com/probonopd/AppImages/blob/master/excludelist)...

**Comment by SkyzohKey** [comment]
@probonopd May u log into irc as we can discuss that more easily plz ?

**Comment by smaragdus** [comment]
I am aware that this is not the right place to ask but I do not want to start a new thread.
I would like to ask- is the Windows version of Ricin abandoned? Or the development is temporarily put on hold?

**Comment by SkyzohKey** [comment]
@smaragdus The windows version will be updated soon, just time for me to find how to setup appveyor to automate the builds ;)

**Comment by smaragdus** [comment]
@SkyzohKey 

Thanks for your response.

I tested Ricin version 0.1.0 for Windows and I encountered a problem- it crashes any time I try to change "Default save path"- please see the screen-shot:

https://i.imgbox.com/deAvcZG0.png

Also I have a few suggestions:
- you may enable the use of "Enter" key in stead of clicking "Login" button.
- please try to get rid of the console window- it is very ugly.
- currently Ricin saves data and settings in AppData ("avatars" folder plus "name.tox" and "ricin.json" files)- please either provide an option to run Ricin in portable mode (saving data and settings in program folder) or release a dedicated portable version of Ricin which saves data and settings in its program folder.

If you release a new version of Ricin for Windows I will test it again. My system- Windows 8 x64.

**Comment by strixaluco** [comment]
@SkyzohKey thanks, I'll try on Stretch later, as I'm on Jessie now.

**Comment by SkyzohKey** [comment]
@smaragdus The issues you listed are solved since long, but yeah I need to make a 0.2.8 build. I'll add the portable mode too, could works I guess.
@strixaluco I'll see why I doesn't have Jessie packages, looks weird :o

**Comment by SkyzohKey** [comment]
@strixaluco Ok .appimage for 0.2.8 is now available, but there is an issue with icons that doesn't shows, dunno why. @probonopd you already had solved this bug, how ? :(

**Comment by probonopd** [comment]
Icon generation has been removed from the AppImage runtime, since the optional `appimaged` daemon will handle desktop integration from now on. It was a hack anyway.

**Comment by SkyzohKey** [comment]
i'm speaking about the icons inside the app :x

**Comment by probonopd** [comment]
How is the app locating them? Using absolute paths?

**Comment by SkyzohKey** [comment]
using gtk3 icons :/

**Comment by probonopd** [comment]
Yes, how does the code do the lookup in the filesystem?

**Comment by SkyzohKey** [comment]
It doesn't, gtk handles that for me. I simplye specify an icon name ie. `contact-new.symbolic` and gtk loads the icon from user theme

**Comment by probonopd** [comment]
Is there a way in GTK to teach it to load icons relative to the binary executable rather than from a hardcoded `/usr` path determined at GTK compile time?

**Comment by SkyzohKey** [comment]
@probonopd I dunno that, gonna ask on IRC.

**Comment by SkyzohKey** [comment]
@probonopd Log from IRC:

```
<SkyzohKey> Is there a way in GTK to teach it to load icons relative to the binary executable rather than from a hardcoded /usr path determined at GTK compile time?
<SkyzohKey> else icons don't appears in .appimage files :x
<ebassi> SkyzohKey: What do you mean "load icons"? GtkIconTheme?
<ebassi> SkyzohKey: See: gtk_icon_theme_append_search_path() and gtk_icon_theme_prepend_search_path()
<ebassi> SkyzohKey: If your application can detect whether or not it's running under appimage, then you can tweak the search paths
<SkyzohKey> should be doable using -D flag i guess
<ebassi> SkyzohKey: Otherwise you'll have to change things like the XDG_DATA_DIRS environment variable before launching your application
```

**Comment by probonopd** [comment]
`XDG_DATA_DIRS` seems to be the way to go - AppRun.c [should](https://github.com/probonopd/AppImageKit/blob/a49019dd6813298364554cb2d673f9a0be6e79f9/AppRun.c#L129-L131) set it to usr/share inside the AppDir.

**Comment by SkyzohKey** [comment]
Didn't understand what you said, is that something related to appimage ?

**Comment by probonopd** [comment]
What I meant to say is that when the AppImage contains an AppRun file compiled from AppRun.c, then it should have the correct value for `XDG_DATA_DIRS` set and hence should load the correct icons - but seemingly isn't, which is puzzling me.

**Comment by strixaluco** [comment]
@SkyzohKey @probonopd thanks a lot for fixes, guys. Now new builds are accessible, so I will close this issue. Hope nobody minds.
