### ISSUE TITLE
Calls and smiles don't work

### ISSUE THREAD

**Issue by zezic** [RicinApp/Ricin#152]
## Summary
* **Operating System + version:** Ubuntu 16.04
* **Ricin's version:** 0.2.7, 0.2.8 and ec38fec builded myself
* **Ricin's commit hash:** ec38fec
* **GTK+ version:** 3.18.9
* **ToxCore version:** 0.1.3769.dcf2aaa-1
* **Hardware:** ASUS UX305FA with Intel Core M-5Y10
* **Reproducible:** Always

## Steps to reproduce:
1. Open chat with contact
2. Try to press call button or smile in smiyles dropdown
3. ...
4. Nothing happens. No console messages.

## Observed Behavior:
Nothing happens.

## Expected Behavior:
Audio/video call should started or smile should placed in text input box.

**Comment by SkyzohKey** [comment]
Yeah these features are not yet implemented in Ricin, i should probably disable the not yet working buttons until it's done, just forgot to do it. 

This issue is not an issue, thus closing. Sorry for the misleading UI :p

**Comment by zezic** [comment]
Lol, guys, may be you should fix info at http://ricin.im/ to match really implemented features? Or at least add checklist with features status to repo?

**Comment by SkyzohKey** [comment]
@zezic Yeah that's just here to being able to make translations more easily, also I plan to implement a/v/emojis soon so it'll take sense ;)

**Comment by zezic** [comment]
@SkyzohKey OK, sorry for false alarm and thank you for nice customizable app!
