### ISSUE TITLE
Losed all the issue when recreating the new repo. :x

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#2]

**Comment by benwaffle** [comment]
oops

**Comment by benwaffle** [comment]
it's fine tho

**Comment by SkyzohKey** [comment]
Yep, will have to recreate them (using browser cache ^^)

**Comment by benwaffle** [comment]
no, we'll create new ones as issues come up

**Comment by SkyzohKey** [comment]
They were some usefull issues :x
It was much suggestions nor issues but...
