### ISSUE TITLE
Wrapper should be coded in separated files.

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#29]
I was thinking about restructuring the whole wrapper, currently it's all in one file. Maybe should we have a folder/repo `wrapper` that would handle the Tox API (friends, files, avatars, messages, audio, video, groups, dns, etc)
##

**Comment by benwaffle** [comment]
when we add audio, video, groupchats

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

Note: That's currently done in the `rewrite-clean` branch.
