### ISSUE TITLE
Markdown support.

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#30]
Ricin should provide a way to use (basic) Markdown to format messages. This is not really hard to do but the real issue is for client compatibility. I guess this shouldn't be a major issue since markdown was reflexed to be readable, even in plaintext.

(Pseudo-) Markdown "balises" we could provide:
- [x] `**bold** text` : Permit to **bold** a message's part.
- [x] `_italic_ text` : Permit to _italicize_ a message's part.
- [x] `~~striked~~ text` : Permit to ~~strike~~ a message's part.
- [x] `--underlined-- text` : Permit to <ins>underline</ins> a message's part.

Ricin (with Markdown lite support):
![Current Ricin's Markdown support](http://i.imgur.com/fS0KB1p.png)

µTox (with no Markdown support):
![Current µTox Markdown support: null](http://i.imgur.com/rTPelaW.png)

**Also, see the qTox issue about that:** https://github.com/tux3/qTox/issues/2497
**It was an issue opened on Tox-STS repo:** https://github.com/Tox-Archive/Tox-STS/issues/74
**And @subliun opened a new issue:** https://github.com/Tox/Tox-Client-Standard/issues/19

**Comment by SkyzohKey** [comment]
Ricin now supports **bolded**, _italicized_, <ins>underlined</ins> and ~~striked~~ messages. 
See the [wip/chatform](https://github.com/RicinApp/Ricin/tree/wip/chatform)@[2e7d6a0](https://github.com/RicinApp/Ricin/commit/2e7d6a0895aa75200a3bd63f19999cf0fcc404d1) commit for more infos.

**Comment by rugk** [comment]
It should also support `naming [links](https://en.wikipedia.org/wiki/Hyperlink)`.

**Comment by SkyzohKey** [comment]
[**@rugk**](https://github.com/rugk) commented on [21 Nov 2015, 12:51 GMT+1](https://github.com/RicinApp/Ricin/issues/30#issuecomment-158632764):

> It should also support `naming [links](https://en.wikipedia.org/wiki/Hyperlink)`.

Hmm, I guess this is a bad idea cuz it would permit people to "spoof" links. What if someone send you a link like: `[https://www.youtube.com/watch?v=dQw4w9WgXcQ](http://iplogger.com/id)` ?

**Comment by gmscs** [comment]
hovering over the named link should give the link itself

**Comment by SkyzohKey** [comment]
@gmscs Hmm, maybe i should add this so.

**Comment by SkyzohKey** [comment]
This can be closed since this comment seems to be the one that will be approved → https://github.com/Tox/Tox-Client-Standard/pull/25#issuecomment-189645287
