### ISSUE TITLE
Is Ricin abandoned?

### ISSUE THREAD

**Issue by Renha** [RicinApp/Ricin#32]
Hello Key, i cannot log in into groupchat (not Ricin fault, at any client), and I came here, and see last commit was 20 days ago. Why? (and don't you have an idea why i couldn't log in?)

And I wanna try Ricin on Windows, but i can't find built version. Does it exists?

**Comment by benwaffle** [comment]
- Ricin isn't abandoned, just inactive for now
- Ricin doesn't support groupchats yet
- Ricin aims to be a Linux client. It might work on Windows but we don't test it and Windows is not our first priority.

**Comment by SkyzohKey** [comment]
Hey @Renha. I'm currently busy in my personal life so I can't work on Rockin yet. When I'll got time my first commit will be to add new group chats and profiles encryptions.. When these two features would be available I'll work on Windows/OSX
