### ISSUE TITLE
Add User Editor View

### ISSUE THREAD

**Issue by gmscs** [RicinApp/Ricin#37]
The user should have a view where they are able to edit the information to their profile. In this view we should have:
- [x] Encrypt/Decrypt profile
- [x] Name edit
- [x] Status message edit
- [x] Set avatar
- [ ] Qr code (for sharing with mobile devices)
- [ ] Import/Export profile
- [ ] Remove avatar
##

**Comment by SkyzohKey** [comment]
I marked it as **priority top**, since we have to focus on this list. :)

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.
