### ISSUE TITLE
Code and folders structure improvements.

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#48]
I think we should rewrite most of Ricin's code to follow these simple rules.
## Code files cleaning

A class constructor method **must suit** the following **conventions**:

``` vala
[GtkTemplate (ui = "/path/to/layout.ui")]
class MyClass {
  // GTK members first.
  [GtkChild] Gtk.Button button_something;

  // Public members.
  public int some_int = 0;

  // Private members.
  private string baz = "";

  public MyObject (string foo, int bar = 0) {
    // Class variables assignements (only).
    this.baz = @"$foo:$bar";

    // Init methods calls.
    this.init_window   ();
    this.init_widgets  ();
    this.init_signals  ();
    this.init_whatever ();
  }

  private void init_window   () { /* Init the windows stuff here  */ }
  private void init_widgets  () { /* Init the widgets stuffs here */ }
  private void init_signals  () { /* Init the signals here        */ }
  private void init_whatever () { /* Init whatever u want         */ }

  ~MyObject () { /* Destructor at the end of the file */ }
}
```
## Directory structure

We should categorize files in the `src/` folder. This would permit to have a more organized code, being more modulable.

**See the example:**

```
src/
-| widgets/
  -| MessageListRow.vala
  -| FriendListRow.vala
  -| GroupListRow.vala
  -| InlineFileMessageListRow.vala
-| Ricin.vala
-| MainWindow.vala
-| Utils.vala
```
##

**Comment by benwaffle** [comment]
GTK automatically connects widgets to private fields and signals to methods if you use `[GtkTemplate]`

**Comment by SkyzohKey** [comment]
Their is not only GTK signals to handle (ie. tox signals connecting). Also the `init_widgets ();` method would be used to set default values for labels, setting a switch on/off based on the value in the config file, etc... We already use GtkTemplate , so.

**Comment by Ogromny** [comment]
@benwaffle fuck men, you code like a piece of shit...

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
Note that I'm working on the `rewrite-clean` branch in order to achieve the result wanted by this issue.
