### ISSUE TITLE
Being able to select more than one message in the chatview.

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#49]
**Note for myself:** This can be accomplished by creating a new Widget and using Pango for text rendering. The hard part with Pango is to make the text selectionnable without issues. Or maybe it should be possible to extend a GtkLabel to do the job. Or even a GtkTextView (iirc the name)
##

**Comment by SkyzohKey** [comment]
I opened the [feature/chatview-rewrite branch](https://github.com/RicinApp/Ricin/tree/feature/chatview-rewrite) for that purpose.

**Comment by benwaffle** [comment]
Don't use pango, use GtkTextView

You can look at [polari](htttps://github.com/gnome/polari), it uses GtkTextView do display the irc messages

**Comment by SkyzohKey** [comment]
Yep, that's what is planned ;). I still don't know how to make "columns" (Name | Message | Timestamp) with GtkTextView but i would like to have something like that.

**Comment by SkyzohKey** [comment]
@benwaffle Do u know how to accomplish this type of "layout" inside a GtkTextView ?

**Comment by benwaffle** [comment]
[check how polari does it](https://github.com/gnome/polari/blob/master/src%2FchatView.js)
