### ISSUE TITLE
if there is no  ~/.config/tox directory, ricin can not start up

### ISSUE THREAD

**Issue by SilverRainZ** [RicinApp/Ricin#55]
`** (ricin:2949): CRITICAL **: file /home/la/aur/ricin-git/src/Ricin/src/Ricin.vala: line 19: uncaught error: Error opening file '/home/la/.config/tox/ricin.cfg': No such file or directory (g-io-error-quark, 1)`

I think it would be better to create a `tox` directory when it is no exist.

btw: I have made a package for ricin, Arch Linux user can install ricin from https://aur.archlinux.org/packages/ricin-git/ (git version)

**Comment by SkyzohKey** [comment]
Ah, thanks for reporting the issue. I'll fix this ;)
Also, thanks for the package, note that we have a .desktop file and an icon now →
- [Icon](https://github.com/RicinApp/Ricin/blob/master/res/images/icons/Ricin-128x128.png)
- [.desktop file](https://github.com/RicinApp/Ricin/blob/master/misc/ricin.desktop)

**Comment by SilverRainZ** [comment]
ok, I will update it.

**Comment by SkyzohKey** [comment]
could you add the `instant messaging` keywords plz ? :)

**Comment by SilverRainZ** [comment]
IM means Instant messaging, isn't it?

**Comment by SkyzohKey** [comment]
Yeah, but `instant messaging` keyword seems to show only real IM, not libs/apps that contains the word IM ^^. It's a little SEO optimisation for people looking for it on Google/DuckDuckGo :p

**Comment by SilverRainZ** [comment]
added, keywords split by space so I use `instant-messaging
but in AUR, when you search for 'instant messaging' keywords, you get few thing。

**Comment by SkyzohKey** [comment]
Yeah, that's the goal ;).
I added your package on the Readme.md file ;)

**Comment by SilverRainZ** [comment]
btw, is valac a runtime dependenic of ricin?
I think it should be a build dependenic because i can run ricin without it.

and just use `yaourt -S ricin-git` that you can install ricin in Arch Linux. (yaourt is a AUR helper)

**Comment by SkyzohKey** [comment]
Yep, valac is the Vala compiler ;).
I'll add this line, isn't pacman doing the same as yaourt ?

**Comment by SilverRainZ** [comment]
no.

pacman only install package from offical software repo (or install a local package).

yaourt is a frontend of pacman, it fetch build script of unoffical software repo (we call it AUR) and auto build a package from build script, then call pacman to install this package.

**Comment by SkyzohKey** [comment]
Ah! Ok seems nice, i'll add `yaourt -S ricin-git` to the readme ;)
