### ISSUE TITLE
Releases are missing submodules.

### ISSUE THREAD

**Issue by SilverRainZ** [RicinApp/Ricin#56]

**Comment by SkyzohKey** [comment]
Hmm. The release archive was created by github, so it's a bug with GitHub :x

**Comment by SkyzohKey** [comment]
Link for reference: http://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release

**Comment by SilverRainZ** [comment]
I am happy to see that the submodule `tox-vapi` became to `vapi` folder,  it makes package more easier, but it seem that the newest release 0.0.4 still haves this submodule.

if there is a release which has remove git submodule, plz @ me, I can package a release package 
immediately.

p.s: if you do some changes that maybe break package (such as: change the way of complile, add new dependiences), I will be glad if you can remind me.

**Comment by SkyzohKey** [comment]
@LastAvenger I just made a release that doesn't needs submodules → https://github.com/RicinApp/Ricin/releases/tag/v0.0.4.1

**Comment by SilverRainZ** [comment]
ok, Arch Linux user can install ricin's lastest release by using `yaourt -S ricin`

https://aur.archlinux.org/packages/ricin/

**Comment by SkyzohKey** [comment]
Thanks for maintaining the package!
Anyway it seems your `PKGBUILD` file doesn't run `ninja install` that would surely introduce regressions (no .desktop, no translations, no icons) ^^

**Comment by SilverRainZ** [comment]
@SkyzohKey `ninjia install` is runned by `make install`, doesn't it?

here is a list that file will be installed in system:

```
ricin /usr/
ricin /usr/bin/
ricin /usr/bin/Ricin
ricin /usr/bin/ricin
ricin /usr/share/
ricin /usr/share/applications/
ricin /usr/share/applications/ricin.desktop
ricin /usr/share/icons/
ricin /usr/share/icons/Ricin-128x128.png
ricin /usr/share/locale/
ricin /usr/share/locale/da_DK/
ricin /usr/share/locale/da_DK/LC_MESSAGES/
ricin /usr/share/locale/da_DK/LC_MESSAGES/ricin.mo
ricin /usr/share/locale/de/
ricin /usr/share/locale/de/LC_MESSAGES/
ricin /usr/share/locale/de/LC_MESSAGES/ricin.mo
ricin /usr/share/locale/en_US/
ricin /usr/share/locale/en_US/LC_MESSAGES/
ricin /usr/share/locale/en_US/LC_MESSAGES/ricin.mo
ricin /usr/share/locale/eo/
ricin /usr/share/locale/eo/LC_MESSAGES/
ricin /usr/share/locale/eo/LC_MESSAGES/ricin.mo
ricin /usr/share/locale/fr_FR/
ricin /usr/share/locale/fr_FR/LC_MESSAGES/
ricin /usr/share/locale/fr_FR/LC_MESSAGES/ricin.mo
ricin /usr/share/locale/pt_PT/
ricin /usr/share/locale/pt_PT/LC_MESSAGES/
ricin /usr/share/locale/pt_PT/LC_MESSAGES/ricin.mo
ricin /usr/share/locale/zh_CN/
ricin /usr/share/locale/zh_CN/LC_MESSAGES/
ricin /usr/share/locale/zh_CN/LC_MESSAGES/ricin.mo
```

**Comment by SkyzohKey** [comment]
Yep, that's right :)

**Comment by SkyzohKey** [comment]
@LastAvenger Ricin 0.0.6 doesn't needs libconfig anymore, you can remove it from the ricin pkg :p

**Comment by SilverRainZ** [comment]
updated. :-)
