### ISSUE TITLE
Legacy icon tray needs improvements.

### ISSUE THREAD

**Issue by Ogromny** [RicinApp/Ricin#58]
- [x] Clicking the legacy icon tray should toggle Ricin's main windows visibility.
- [x] Icons needs to be updated.

**Comment by benwaffle** [comment]
FYI GNOME calls it the legacy icon tray

**Comment by benwaffle** [comment]
https://elementary.io/docs/human-interface-guidelines#does-your-app-need-an-indicator

Ricin doesn't need an indicator. It should probably integrate with the messaging menu that is present on some DEs
