### ISSUE TITLE
Add an emoticon selection box

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#64]
This is a **sample** mockup that's coded (.ui + popover code done) : 
![Mockup](http://i.imgur.com/a5IStBp.png)
##

**Comment by Ogromny** [comment]
Oh it's amazing ! Love it :)

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.
