### ISSUE TITLE
Setup a buildbot at https://build.ricin.im

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#66]
##

**Comment by benwaffle** [comment]
why not build.tox.chat

**Comment by optimumtact** [comment]
@benwaffle the distros we chose to use for the jenkins are not easily able to build the ricin app thanks to missing packages and other dependency issues.

**Comment by SkyzohKey** [comment]
@benwaffle @optimumtact + Infrastructure costs needs to be put down :p

**Comment by SkyzohKey** [comment]
Outdated since travis is now working fine.
