### ISSUE TITLE
Can't load the profile - unable to bind to a port

### ISSUE THREAD

**Issue by ovalseven8** [RicinApp/Ricin#68]
## Summary
- **Operating System:** Manjaro Linux
- **Ricin's version:** https://github.com/RicinApp/Ricin/commit/a05c0ca54c35224b132f81997d49b56d0824dd97
- **Reproducible:** Always
## Steps to reproduce:
1. Install Ricin 

```
git clone --recursive https://github.com/RicinApp/Ricin.git && cd Ricin
make autogen
sudo make install
```
1. Start Ricin
2. Try to create a new profile
3. Error:

```
** (Ricin:4480): WARNING **: MainWindow.vala:84: Tox init failed: The function was unable to bind to a port.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

** (Ricin:4480): CRITICAL **: tox_wrapper_tox_save_data: assertion 'self != NULL' failed
```
##

**Comment by SkyzohKey** [comment]
Ricin do not deals with network so I assume this a ToxCore issue, closed.

**Comment by tr37ion** [comment]
I have the same issue with Arch and the git version for weeks. This is my terminal output:
`
*\* (ricin:15053): WARNING **: MainWindow.vala:97: Tox init failed: The function was unable to bind to a port.

*\* (ricin:15053): CRITICAL **: tox_wrapper_tox_save_data: assertion 'self != NULL' failed

*\* (ricin:15053): CRITICAL **: tox_wrapper_tox_disconnect: assertion 'self != NULL' failed
`

**Comment by SkyzohKey** [comment]
@tr37ion I asked @irungentoo about this and IIRC he told me that this was an error message that appears when you have too many Tox clients opened at the same time. Is it your case?

Here's the issue "documentation":
![ERR_NEW_PORT_ALLOC](http://i.imgur.com/mt47McF.png)

**Comment by tr37ion** [comment]
No, there is no other tox client running at the same time? Or do you mean, too many clients installed in general?

**Comment by SkyzohKey** [comment]
@tr37ion If I understand the error message correctly, this would means the following things: All the ports Tox tries to use are already used by others Tox clients, or by others apps. Can you reproduce the issue with uTox/qTox ?
