### ISSUE TITLE
Trying to run latest binary from ricin.im

### ISSUE THREAD

**Issue by dcharles525** [RicinApp/Ricin#73]
When trying to run the binary, I keep getting this error:

./Ricin: error while loading shared libraries: libconfig.so.9: cannot open shared object file: No such file or directory

Any idea why? Running Elementary OS, latest.
##

**Comment by gmscs** [comment]
Have you installed libconfig9?
`sudo apt-get install libconfig9`

**Comment by dcharles525** [comment]
Whoops, ok I installed that, but now I am getting this error:

``` log
**(Ricin:4512): Gtk-WARNING**: Locale not supported by C library.
    Using the fallback 'C' locale.

**(Ricin:4512): WARNING**: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-GubKxp4PsN: Connection refused
./Ricin: symbol lookup error: ./Ricin: undefined symbol: gtk_css_provider_load_from_resource
```

**Comment by SkyzohKey** [comment]
@dcharles525 Looks like the binary is missing resources, I'll investigate. :)

**Comment by benwaffle** [comment]
don't use the binary from the website, compile it from source

**Comment by SkyzohKey** [comment]
@benwaffle The binary from the website is generated with [this script](https://github.com/RicinApp/Ricin/blob/wip/bubbles/tools/build_linux_package.sh). It have to work ;)

**Comment by benwaffle** [comment]
We don't have any c++ code, why do you have -static-libstdc++

**Comment by SkyzohKey** [comment]
Took the sample from meson repository, forgot to remove it :/

**Comment by SkyzohKey** [comment]
Bump.
@dcharles525 What GTK+ version are you running?

**Comment by dcharles525** [comment]
@SkyzohKey sorry for the slow response.

Version: 2.24.23-0ubuntu1.4

**Comment by SkyzohKey** [comment]
Ok so that's absolutly normal since you need at least GTK+3.18 to have Ricin running. x)

**Comment by benwaffle** [comment]
That is GTK2, what version of GTK3 do you have?
