### ISSUE TITLE
Ricin won't build

### ISSUE THREAD

**Issue by katamari1992** [RicinApp/Ricin#74]
## Summary

Linux Mint 17.3
newest
- **Hardware:** _…_

Always
## Steps to reproduce:
1.  build
2.  I've been trying to compile ricin on linux mint 17.3 
   I believe I've got all the deps (unsure how to check for all the deps all at once) 
   I keep getting an error when trying to build Any help would be appreciated
   edit: I check for all the deps and they all seem to be there

rm -rf ./build
mkdir -p ./build
meson . ./build
The Meson build system
 version: 0.16.0
Source dir: /home/katamari/Downloads/Ricin-master
Build dir: /home/katamari/Downloads/Ricin-master/build
Build type: native build
Project name is "Ricin".
Using native vala compiler "valac". (unknown 0.22.1)
Using native c compiler "cc". (gcc 4.8.4)

Meson encountered an error in file meson.build, line 6, column 0:
Unknown function "import".
make: **\* [autogen] Error 1
1.  commenting out line 6 or removing it entirely also does not get rid of the error
## Additional infos:

_(links, images, etc go here)_

**Comment by benwaffle** [comment]
You need to update `meson`

**Comment by katamari1992** [comment]
as far as aptitude or apt-get is concerned it is up to date however I will try building from source

**Comment by benwaffle** [comment]
I have meson 0.30 on my system. Try installing from pip

**Comment by katamari1992** [comment]
PROGRESS! yay! ty now onto the next issue
edit error 127 meson not in PATH 
dunno how to fix that googling now
edit edit: nvm it completelly failed to install

rm -rf ./build
mkdir -p ./build
meson . ./build
make: meson: Command not found
make: **\* [autogen] Error 127

edit edit edit:
   File "/usr/local/lib/python2.7/dist-packages/mesonbuild/mlog.py", line 73
        print(_arr, file=log_file, *_kwargs) # Log file never gets ANSI codes.
              ^
    SyntaxError: invalid syntax

```
  File "/usr/local/lib/python2.7/dist-packages/mesonbuild/mgui.py", line 360
    return self.ui.exec()
                      ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/mesonbuild/wrap/wrap.py", line 49
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
```

I'm lost plz halp

**Comment by benwaffle** [comment]
This looks like an error in python or meson. Please file a bug at https://github.com/mesonbuild/meson/issues

**Comment by katamari1992** [comment]
Ty for your help

**Comment by SkyzohKey** [comment]
@katamari1992 Meson needs to be installed from Python3, u're using Python2.7. ;)

**Comment by katamari1992** [comment]
ok I have/had python3 but I also have python 2.7 as reported by synaptic 
Can I force the build tools to use python3?
I uninstalled 2.7 and I get the same error

**Comment by SkyzohKey** [comment]
just install it from sources:

```
$ git clone https://github.com/mesonbuild/meson.git
$ cd meson
$ python3 setup.py install # It'll probably ask u to run using sudo.
```

or using `pip3`

```
$ pip3 install meson
```

**Comment by katamari1992** [comment]
I installed using your method but I'm still getting this error

rm -rf ./build
mkdir -p ./build
meson . ./build
make: meson: Command not found
make: **\* [autogen] Error 127

**Comment by SkyzohKey** [comment]
Hmm, weird. Did u used `pip3` or sources ?

**Comment by katamari1992** [comment]
I used the three lines you provided above to install meson
I am attempting to install ricin via sources 
(dependancies are questionable but I seem to have all of them)
take note that I am using linux mint 17.3 which is based on ubuntu's trusty which is outdated
edit: meson appears to not have installed ... irratating sources!

**Comment by SkyzohKey** [comment]
Dependencies are all listed on the [README.md file](../README.md). Could u please try to install meson using `pip3 install meson` ?

**Comment by katamari1992** [comment]
katamari@Moya ~ $ sudo pip3 install meson
Requirement already satisfied (use --upgrade to upgrade): meson in /usr/local/lib/python3.4/dist-packages
Cleaning up...

katamari@Moya ~ $ sudo dpkg --list | grep meson
katamari@Moya ~ $ 

http://paste2.org/L03b32gJ
I have like 3 of the dependancies met the others are installed but outdated I'll report back tomorrow Ima go get high on nyquil

**Comment by SkyzohKey** [comment]
Yeah, nice, now try this in the Ricin directory

```
$ make autogen
$ make install
```

**Comment by katamari1992** [comment]
katamari@Moya ~/Downloads/Ricin-master $ make autogen
rm -rf ./build
mkdir -p ./build
meson . ./build
make: meson: Command not found
make: **\* [autogen] Error 127
katamari@Moya ~/Downloads/Ricin-master $ make install
cd build/ && type ninja-build 2>/dev/null && ninja-build install || ninja install
ninja-build: not found
ninja: error: loading 'build.ninja': No such file or directory
make: **\* [install] Error 1

**Comment by SkyzohKey** [comment]
Hmm, what the hell...
Let's try something (maybe stupid but we'll see if that works):

```
$ locate meson
```

**Comment by katamari1992** [comment]
http://paste2.org/L5bEEAGJ

**Comment by SkyzohKey** [comment]
Ok right, maybe could I provide u support over [Gitter](https://gitter.im/RicinApp/Ricin) ?
