### ISSUE TITLE
Problem install Elementary OS

### ISSUE THREAD

**Issue by Codecombay** [RicinApp/Ricin#76]
Hello,

Impossible install Ricin in Elementary OS.

`sudo apt-get install libglib2.0-0 libglib2.0-dev libjson-glib-1.0-0 libjson-glib-dev libsoup-gnome2.4-dev libnotify-dev`

After

```
➜  Ricin git:(master) make autogen
rm -rf ./build
mkdir -p ./build
meson . ./build
**make: meson: commande introuvable
make: *** [autogen] Erreur 127**
```
##

**Comment by SkyzohKey** [comment]
Je suppose que tu es Français vu ton anglais. Le problème ici est que tu n'as pas installé meson. Essaye la chose suivante :

I guess you're french, seeing your english. The problem here is that you didn't installed meson.
Try the following:

``` bash
$ sudo apt-get install pip3 valac
$ sudo pip3 install meson
```

**Comment by Codecombay** [comment]
J'ai fais l'installation de tous.
J'ai encore la même erreur.
"man meson" marche correctement, alors que meson --version ne marche pas...

**Comment by SkyzohKey** [comment]
OK. Que se passe-t-il quand tu fais un `/usr/bin/meson --version` ?

**Comment by Codecombay** [comment]
`zsh: aucun fichier ou dossier de ce type: /usr/bin/meson`

**Comment by SkyzohKey** [comment]
Un coup de `locate meson` histoire de voir ?

**Comment by Codecombay** [comment]
locate meson
/home/xana/Documents/tmp/truc/Ricin/meson.build
/home/xana/Documents/tmp/truc/Ricin/po/meson.build
/home/xana/Documents/tmp/truc/Ricin/res/meson.build
/home/xana/Documents/tmp/truc/Ricin/src/meson.build
/usr/src/linux-headers-3.19.0-39/arch/arm/mach-meson
/usr/src/linux-headers-3.19.0-39/arch/arm/include/debug/meson.S
/usr/src/linux-headers-3.19.0-39/arch/arm/mach-meson/Kconfig
/usr/src/linux-headers-3.19.0-39/arch/arm/mach-meson/Makefile
/usr/src/linux-headers-3.19.0-56/arch/arm/mach-meson
/usr/src/linux-headers-3.19.0-56/arch/arm/include/debug/meson.S
/usr/src/linux-headers-3.19.0-56/arch/arm/mach-meson/Kconfig
/usr/src/linux-headers-3.19.0-56/arch/arm/mach-meson/Makefile

**Comment by SkyzohKey** [comment]
ok, donc meson n'est pas installé sur ton système. Essaie de compiler à partir des sources dans ce cas:

``` bash
cd /tmp
git clone https://github.com/mesonbuild/meson.git && cd meson
sudo python3 setup.py install
```

**Comment by Codecombay** [comment]
Même erreur :(

**Comment by SkyzohKey** [comment]
La compilation de meson se passe comment du coup ? Des erreurs ?
Sinon, il faudra ouvrir une issue sur le [bug-tracker de MesonBuild](https://github.com/mesonbuild/meson/issues). :/
