### ISSUE TITLE
Autoscroll not working

### ISSUE THREAD

**Issue by Sorunome** [RicinApp/Ricin#79]
## Summary
- **Operating System:** Archlinux
- **Ricin's version:** 0.0.3-beta
- **Reproducible:** Almost Always
## Steps to reproduce:
1.  fill the box so that you need to scroll
2. have the other chat partner say something
3. say something yourself and it won't autoscroll
   Sometimes it will also not autoscroll when the other person writes something
##

**Comment by Sorunome** [comment]
Maybe this has to do with the typing notification as not always when the notification appears the text area slides up but sometimes it slides down when it diss-appears and other weired stuff.

**Comment by SkyzohKey** [comment]
Yep. I'll work on this today. This is really borring I admit :/
