### ISSUE TITLE
URL parsing

### ISSUE THREAD

**Issue by Sorunome** [RicinApp/Ricin#80]
when you parse a link like https://ricin.im/ it will first parse the italics and then url or something so that it'll actually open `https://<i>ricin.im</i>` in the browser
##

**Comment by SkyzohKey** [comment]
Hi, thanks for the bug report! This is a known issue caused by the way Ricin handles Markdown (shitty regexes). I'll need to write a proper Markdown parser in order to have things working perfectly.

**Comment by SkyzohKey** [comment]
@Sorunome The issue have been fixed with 0.0.5 (new settings pr) I guess, feel free to reopen if you think the bug is still here. ;)

**Comment by Sorunome** [comment]
bug is still there, happens if you have http:// &lt;url&gt; /

So if there is a trailing slash after the URL but no additional path

**Comment by SkyzohKey** [comment]
Ah! Shiiiiiiiiiiiiit. I reopen then x)

**Comment by SkyzohKey** [comment]
That's fixed. :)
