### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by Derpolino** [RicinApp/Ricin#81]
I'm still waiting the Windows version, uTox continues to be shit and keeps reseting my profile. I'd really like to use Ricin on Windows.
##

**Comment by SkyzohKey** [comment]
Their is still an issue with glib-gresources, I guess i'll switch from the Meson Build System to WAF/Autotools in order to have it compiling well on Windoesn't too. :)

**Comment by SkyzohKey** [comment]
I'm currently working hard on making a first .exe version for Windoesn't.: )

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
Note that you now can download a preview of Ricin running on windows at https://ricin.im :)
