### ISSUE TITLE
Option to disable markdown and smileys

### ISSUE THREAD

**Issue by Sorunome** [RicinApp/Ricin#92]
Maybe add an option to disable the markdown and smiley parsing?

**Comment by SkyzohKey** [comment]
This is planed, but I first need to rewrite the way ChatView acts. Currently it's a simple ListBox with custom ListBoxRow's. I plan rewriting it using TextView or Pango. ;)

**Comment by SkyzohKey** [comment]
This has been implemented as `Message parsing mode` in latest `0.2.5` Ricin's master release, thus closing :)
