### ISSUE TITLE
Impossible de lancer Ricin

### ISSUE THREAD

**Issue by Ogromny** [RicinApp/Ricin#94]
Depuis la dernière MAJ je ne peux plus lancer Ricin :(

``` bash
(Ricin:9175): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
Fontconfig warning: ignoring ޙ: not a valid language tag
fish: 'Ricin' terminated by signal SIGSEGV (Erreur de frontière d'adresse)
```

Je précise que je suis sous gnome 3.19 wayland

**Comment by SkyzohKey** [comment]
Hi !
Simply delete `~/.config/tox/ricin.cfg` then relaunch Ricin. That's a libconfig issue, I really need to rewrite the SettingsManager...

**Edit**: I just added a rule in the Makefile to do this automatically, simply use `make reset-settings`

J'viens de sortir de garde à vue, donc bon :x
