### ISSUE TITLE
Messages appear as "label"

### ISSUE THREAD

**Issue by Sorunome** [RicinApp/Ricin#95]
## Summary
- **Operating System + version:**  Archlinux
- **Ricin's version:**  ricin-git 0.540.62bb688-1
- **Ricin's commit hash:**  ricin-git 0.540.62bb688-1
- **Reproducible:** Randomly
## Observed Behavior:

Sometimes when sending a message or when recieving one it is being displayed as "label", internally the messages still send find / are recieved fine, so it's probably just the displaying part. Unfortunately I haven't found a pattern in this, yet, it just happenes seemingly randomly.

**Comment by SkyzohKey** [comment]
Yeah, this is related to Markdown parsing (again u-u). `label` is the placeholder written in the `.ui` file for the ChatView. When Markdown fails, it returns blank and label isn't updated. I'll fix this, lemme investigate. Thanks for the report ;)
