### ISSUE TITLE
Sent file size is badly calculated

### ISSUE THREAD

**Issue by Ogromny** [RicinApp/Ricin#97]
When sending a file, the size is divided by 1000.
https://i.imgur.com/yYDJNRT.png

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

Note: I'm completly rewriting Ricin, so this issue will be fixed in the `rewrite-clean` branch.
