### ISSUE TITLE
Sidepane toggle is broken

### ISSUE THREAD

**Issue by Ogromny** [RicinApp/Ricin#98]
Normal:
http://i.imgur.com/AVbDMsR.png
After clicked on friend info:
http://i.imgur.com/uI3eikj.png

**Comment by SkyzohKey** [comment]
That seems to be related to how Ricin handle quotes. The bug only appears when their is a quote in the chat, else it works fine.

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

Note: I'm completly rewriting Ricin, so this issue will be fixed in the `rewrite-clean` branch.
